import { expect, test } from '@playwright/test'
import { createServer, type Server } from 'node:http'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { extname, resolve, sep } from 'node:path'
import { createRequire } from 'node:module'

// This suite executes the production service-worker route and the exact
// canonical Next.js artifacts generated by `npm run build:offline-v5`.
// It deliberately never inserts account data in CacheStorage: private data is
// exercised by the encrypted-engine tests instead.
const projectRoot = resolve(__dirname, '..')
const frontendRoot = resolve(projectRoot, 'frontend')
const publicRoot = resolve(frontendRoot, 'public')
const nextStaticRoot = resolve(frontendRoot, '.next/static')
const requireFrontend = createRequire(resolve(frontendRoot, 'package.json'))
const { build } = requireFrontend('esbuild') as typeof import('../frontend/node_modules/esbuild')

let server: Server
let origin = ''
let workerSource = ''
let servedWorkerSource = ''
let originUnavailable = false
let infrastructureStatus = 0
let cloudflareChallenge = false
let trustedDenial = 0
let corruptManifest = false
let cookieSeen = false
const privateSentinel = 'PRIVATE_ACCOUNT_DATA_MUST_NEVER_ENTER_CACHE_V5_451827'
const staleLoginWorkerSource = `
const CACHE = 'clarin-qa-stale-login';
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await cache.put('/stale-login', new Response('<!doctype html><h1>Stale offline login</h1>', { headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Security-Policy': "default-src 'self'; script-src 'self' 'unsafe-inline'",
    } }));
    await self.skipWaiting();
  })());
});
self.addEventListener('activate', event => event.waitUntil(self.clients.claim()));
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.mode === 'navigate' && (url.pathname === '/' || url.pathname === '/login')) {
    event.respondWith(caches.open(CACHE).then(cache => cache.match('/stale-login')));
  }
});
`.trim()

const contentTypes: Record<string, string> = {
  '.css': 'text/css; charset=utf-8',
  '.html': 'text/html; charset=utf-8',
  '.ico': 'image/x-icon',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.png': 'image/png',
  '.rsc': 'text/x-component; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.webmanifest': 'application/manifest+json; charset=utf-8',
  '.woff2': 'font/woff2',
}

function localFile(pathname: string) {
  const root = pathname.startsWith('/_next/static/') ? nextStaticRoot : publicRoot
  const relative = pathname.startsWith('/_next/static/')
    ? pathname.slice('/_next/static/'.length)
    : pathname.slice(1)
  const candidate = resolve(root, relative)
  return candidate.startsWith(root + sep) ? candidate : undefined
}

test.beforeAll(async () => {
  // Fail early with a useful message if QA was invoked before the production
  // build generated the immutable public corpus.
  await readFile(resolve(publicRoot, 'offline-v5/manifest.json'))
  const bundled = await build({
    entryPoints: [resolve(frontendRoot, 'src/app/sw.js/route.ts')],
    bundle: true,
    write: false,
    platform: 'node',
    format: 'cjs',
    tsconfig: resolve(frontendRoot, 'tsconfig.json'),
    define: { 'process.env.NEXT_PUBLIC_BUILD_VERSION': JSON.stringify('qa-canonical-shell-v5') },
  })
  const module = { exports: {} as { GET?: () => Response } }
  new Function('module', 'exports', bundled.outputFiles![0].text)(module, module.exports)
  workerSource = await module.exports.GET!().text()
  servedWorkerSource = workerSource

  server = createServer(async (request, response) => {
    if (originUnavailable) {
      request.socket.destroy()
      return
    }
    try {
      const url = new URL(request.url || '/', origin || 'http://127.0.0.1')
      if (url.pathname === '/sw.js') {
        response.writeHead(200, {
          'Cache-Control': 'no-store',
          'Content-Type': 'application/javascript; charset=utf-8',
          'Service-Worker-Allowed': '/',
        })
        response.end(servedWorkerSource)
        return
      }
      if (url.pathname === '/offline-v5/manifest.json') {
        const manifest = JSON.parse(await readFile(resolve(publicRoot, 'offline-v5/manifest.json'), 'utf8'))
        manifest.app_origin = origin
        manifest.build_id = 'qa-canonical-shell-v5'
        if (corruptManifest) manifest.assets[0].sha256 = '0'.repeat(64)
        response.writeHead(200, { 'Cache-Control': 'no-store', 'Content-Type': 'application/json; charset=utf-8' })
        response.end(JSON.stringify(manifest))
        return
      }
      if (url.pathname.startsWith('/api/')) {
        response.writeHead(200, { 'Cache-Control': 'private, no-store', 'Content-Type': 'application/json', 'X-Clarin-Response': '1' })
        response.end(JSON.stringify({ success: true, fixture: privateSentinel }))
        return
      }

      const file = localFile(url.pathname)
      if (file) {
        try {
          const bytes = await readFile(file)
          response.writeHead(200, {
            'Cache-Control': 'public, max-age=31536000, immutable',
            'Content-Length': bytes.byteLength,
            'Content-Type': contentTypes[extname(file)] || 'application/octet-stream',
          })
          response.end(bytes)
          return
        } catch {
          // Continue to the synthetic online navigation below.
        }
      }

      if (cloudflareChallenge) {
        response.writeHead(403, { 'CF-Mitigated': 'challenge', 'Content-Type': 'text/html' })
        response.end('<h1>Cloudflare challenge fixture</h1>')
        return
      }
      if (trustedDenial) {
        response.writeHead(trustedDenial, { 'Cache-Control': 'private, no-store', 'Content-Type': 'application/json', 'X-Clarin-Response': '1' })
        response.end(JSON.stringify({ error: 'permission_denied' }))
        return
      }
      if (infrastructureStatus) {
        response.writeHead(infrastructureStatus, { 'Content-Type': 'text/html' })
        response.end('<h1>Infrastructure unavailable</h1>')
        return
      }

      cookieSeen ||= (request.headers.cookie || '').includes('qa_navigation=preserve')
      response.writeHead(200, { 'Cache-Control': 'private, no-store', 'Content-Type': 'text/html' })
      response.end(`<!doctype html><html><body><h1>Online fixture</h1><p>${privateSentinel}</p></body></html>`)
    } catch {
      response.writeHead(404).end('Not found')
    }
  })
  await new Promise<void>(resolveListen => server.listen(0, '127.0.0.1', resolveListen))
  const address = server.address()
  if (!address || typeof address === 'string') throw new Error('Offline v5 QA server unavailable')
  origin = `http://127.0.0.1:${address.port}`
})

test.afterAll(async () => {
  await new Promise<void>((resolveClose, reject) => server.close(error => error ? reject(error) : resolveClose()))
})

test.beforeEach(() => {
  servedWorkerSource = workerSource
  originUnavailable = false
  infrastructureStatus = 0
  cloudflareChallenge = false
  trustedDenial = 0
  corruptManifest = false
  cookieSeen = false
})

test('a stale offline login worker promotes the safe update without clearing site data', async ({ page }) => {
  servedWorkerSource = staleLoginWorkerSource
  await page.goto(origin + '/login')
  await page.evaluate(async () => {
    await navigator.serviceWorker.register('/sw.js', { scope: '/', updateViaCache: 'none' })
    await navigator.serviceWorker.ready
  })
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)

  let response = await page.reload({ waitUntil: 'commit' })
  expect(response?.headers()['content-security-policy']).toContain("script-src 'self' 'unsafe-inline'")
  expect(await response!.text()).toContain('Stale offline login')

  servedWorkerSource = workerSource
  await page.evaluate(() => new Promise<void>(async (resolveUpdate, rejectUpdate) => {
    const registration = await navigator.serviceWorker.getRegistration('/')
    if (!registration) {
      rejectUpdate(new Error('service worker registration missing'))
      return
    }
    const timeout = window.setTimeout(() => rejectUpdate(new Error('updated worker stayed waiting')), 15_000)
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      window.clearTimeout(timeout)
      resolveUpdate()
    }, { once: true })
    await registration.update()
  }))

  response = await page.reload({ waitUntil: 'commit' })
  expect(response?.headers()['content-security-policy']).toBeUndefined()
  expect(await response!.text()).toContain('Online fixture')
})

async function message<T>(page: import('@playwright/test').Page, value: Record<string, unknown>): Promise<T> {
  return page.evaluate(payload => new Promise(resolveMessage => {
    const channel = new MessageChannel()
    channel.port1.onmessage = event => {
      channel.port1.close()
      resolveMessage(event.data)
    }
    navigator.serviceWorker.controller!.postMessage(payload, [channel.port2])
  }), value) as Promise<T>
}

async function installWorker(page: import('@playwright/test').Page) {
  await page.goto(origin)
  await page.evaluate(async () => {
    await navigator.serviceWorker.register('/sw.js', { scope: '/' })
    await navigator.serviceWorker.ready
  })
  await page.reload()
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
}

async function prepareWorker(page: import('@playwright/test').Page) {
  await installWorker(page)
  const result = await message<{ ok: boolean; error?: string }>(page, { type: 'CLARIN_OFFLINE_V5_SET_ENABLED', enabled: true })
  expect(result).toEqual({ ok: true })
  await expect.poll(() => page.evaluate(async () => {
    const response = await (await caches.open('clarin-offline-v5-meta-v1')).match('/offline-v5/.runtime-meta.json')
    const meta = response ? await response.json() : undefined
    return Boolean(meta?.enabled && meta?.shell_generations?.length)
  }), { timeout: 180_000 }).toBe(true)
}

async function cachedLeaks(page: import('@playwright/test').Page) {
  return page.evaluate(async sentinel => {
    const leaks: string[] = []
    for (const cacheName of await caches.keys()) {
      const cache = await caches.open(cacheName)
      for (const request of await cache.keys()) {
        if (new URL(request.url).pathname.startsWith('/api/')) leaks.push(`api:${request.url}`)
        const response = await cache.match(request)
        if (response && (await response.clone().text()).includes(sentinel)) leaks.push(`body:${request.url}`)
      }
    }
    return leaks
  }, privateSentinel)
}

test('ordinary browsers receive only the tiny public fallback until an authorized preparation enables v5', async ({ page }) => {
  const requested: string[] = []
  page.on('request', request => {
    const pathname = new URL(request.url()).pathname
    if (pathname.startsWith('/offline-v5/')) requested.push(pathname)
  })
  await installWorker(page)
  expect((await page.evaluate(() => caches.keys())).filter(name => name.startsWith('clarin-offline-v5-shell-'))).toEqual([])
  expect(requested).toEqual([])
})

test('revocation removes every local navigation authority when no prepared copy remains', async ({ page }) => {
  await prepareWorker(page)

  expect((await page.evaluate(() => caches.keys())).some(name => name.startsWith('clarin-offline-v5-shell-'))).toBe(true)
  expect(await message(page, { type: 'CLARIN_OFFLINE_V5_SET_MODE', mode: 'offline' })).toEqual({ ok: true })
  expect(await message(page, { type: 'CLARIN_OFFLINE_V5_CLEAR_LOCAL_AUTHORITY' })).toEqual({ ok: true })

  const status = await message<{
    ok: boolean
    meta: { enabled: boolean; mode: string; fallback_offer: boolean; shell_generations: string[] }
  }>(page, { type: 'CLARIN_OFFLINE_V5_GET_STATUS' })
  expect(status).toMatchObject({
    ok: true,
    meta: { enabled: false, mode: 'online', fallback_offer: false, shell_generations: [] },
  })
  expect((await page.evaluate(() => caches.keys())).filter(name => name.startsWith('clarin-offline-v5-shell-'))).toEqual([])

  const response = await page.goto(origin + '/login', { waitUntil: 'commit' })
  expect(response?.headers()['x-clarin-offline-route']).toBeUndefined()
  expect(await response!.text()).toContain('Online fixture')
})

test('verified v5 stores only public application artifacts and preserves online cookies', async ({ page, context }) => {
  await prepareWorker(page)
  await context.addCookies([{ name: 'qa_navigation', value: 'preserve', url: origin }])
  cookieSeen = false
  await page.goto(origin + '/dashboard/tasks')
  await expect(page.getByRole('heading', { name: 'Online fixture' })).toBeVisible()
  expect(cookieSeen).toBe(true)
  await page.evaluate(() => fetch('/api/private-fixture').then(response => response.json()))
  expect(await cachedLeaks(page)).toEqual([])
})

test('ordinary F5 keeps login online while the selected dashboard remains offline', async ({ page }) => {
  await prepareWorker(page)
  expect(await message(page, { type: 'CLARIN_OFFLINE_V5_SET_MODE', mode: 'offline' })).toEqual({ ok: true })

  let response = await page.goto(origin + '/login', { waitUntil: 'commit' })
  expect(response?.headers()['x-clarin-offline-route']).toBeUndefined()
  expect(await response!.text()).toContain('Online fixture')

  response = await page.reload({ waitUntil: 'commit' })
  expect(response?.headers()['x-clarin-offline-route']).toBeUndefined()
  expect(await response!.text()).toContain('Online fixture')

  response = await page.goto(origin + '/dashboard/tasks', { waitUntil: 'commit' })
  expect(response?.headers()['x-clarin-offline-route']).toBe('tasks')
})

test('same canonical Next routes reopen without network instead of a parallel offline application', async ({ page, context }) => {
  await prepareWorker(page)
  expect(await message(page, { type: 'CLARIN_OFFLINE_V5_SET_MODE', mode: 'offline' })).toEqual({ ok: true })
  const blockedAPI = await page.evaluate(async () => {
    const response = await fetch('/api/contacts')
    return { status: response.status, header: response.headers.get('x-clarin-offline'), body: await response.json() }
  })
  expect(blockedAPI).toMatchObject({ status: 503, header: '5', body: { error: 'offline_network_blocked', offline: true } })
  originUnavailable = true
  await context.setOffline(true)
  for (const [path, route] of [
    ['/login', 'login'],
    ['/dashboard/tasks', 'tasks'],
    ['/dashboard/contacts', 'contacts'],
    ['/dashboard/programs', 'programs'],
    ['/dashboard/whiteboards', 'whiteboards'],
    ['/dashboard/programs/6d40c9c7-fba0-448d-8d74-64245612a7c5', 'program_detail'],
    ['/dashboard/whiteboards/eb15527a-2696-4593-ae25-8639bb201a37', 'whiteboard_detail'],
  ] as const) {
    const response = await page.goto(origin + path, { waitUntil: 'commit' })
    expect(response?.headers()['x-clarin-offline-route']).toBe(route)
    const html = await response!.text()
    expect(html).toContain('self.__next_f')
    expect(html).not.toContain('clarin-offline-root')
    expect(html).not.toContain(privateSentinel)
  }
})

test('Cloudflare/infrastructure failure offers fallback but never unlocks a local identity silently', async ({ page }) => {
  await prepareWorker(page)
  infrastructureStatus = 503
  const response = await page.goto(origin + '/login', { waitUntil: 'commit' })
  expect(response?.headers()['x-clarin-offline-route']).toBe('login')
  const status = await message<{ ok: boolean; meta: { fallback_offer: boolean; mode: string } }>(page, { type: 'CLARIN_OFFLINE_V5_GET_STATUS' })
  expect(status).toMatchObject({ ok: true, meta: { fallback_offer: true, mode: 'online' } })
  expect(await cachedLeaks(page)).toEqual([])
})

test('a Cloudflare challenge is infrastructure failure while trusted Clarin denials remain authoritative', async ({ page }) => {
  await prepareWorker(page)
  cloudflareChallenge = true
  let response = await page.goto(origin + '/login', { waitUntil: 'commit' })
  expect(response?.headers()['x-clarin-offline-route']).toBe('login')

  cloudflareChallenge = false
  trustedDenial = 403
  response = await page.goto(origin + '/dashboard/tasks', { waitUntil: 'commit' })
  expect(response?.status()).toBe(403)
  expect(await response!.text()).toContain('permission_denied')
  expect(response?.headers()['x-clarin-offline-route']).toBeUndefined()
})

test('a fully closed browser can reopen the cached login and canonical dashboard with no installer', async ({ playwright }, testInfo) => {
  const profile = await mkdtemp(resolve(tmpdir(), 'clarin-offline-v5-browser-'))
  const launchOptions = testInfo.project.use.launchOptions || {}
  let persistent = await playwright.chromium.launchPersistentContext(profile, { ...launchOptions, headless: true })
  try {
    const page = persistent.pages()[0] || await persistent.newPage()
    await prepareWorker(page)
    expect(await message(page, { type: 'CLARIN_OFFLINE_V5_SET_MODE', mode: 'offline' })).toEqual({ ok: true })
    await persistent.close()

    originUnavailable = true
    persistent = await playwright.chromium.launchPersistentContext(profile, { ...launchOptions, headless: true })
    const reopened = persistent.pages()[0] || await persistent.newPage()
    let response = await reopened.goto(origin + '/login', { waitUntil: 'commit' })
    expect(response?.headers()['x-clarin-offline-route']).toBe('login')
    response = await reopened.goto(origin + '/dashboard/tasks', { waitUntil: 'commit' })
    expect(response?.headers()['x-clarin-offline-route']).toBe('tasks')
    expect(await response!.text()).not.toContain(privateSentinel)
  } finally {
    originUnavailable = false
    await persistent.close()
    await rm(profile, { recursive: true, force: true })
  }
})

test('a corrupt update cannot replace either of the last two verified public generations', async ({ page, context }) => {
  await prepareWorker(page)
  const previous = await page.evaluate(async () => {
    const response = await (await caches.open('clarin-offline-v5-meta-v1')).match('/offline-v5/.runtime-meta.json')
    return (await response!.json()).shell_generations as string[]
  })
  corruptManifest = true
  expect(await message(page, { type: 'CLARIN_OFFLINE_V5_SET_ENABLED', enabled: true })).toEqual({ ok: false, error: 'offline_shell_unavailable' })
  const after = await page.evaluate(async () => {
    const response = await (await caches.open('clarin-offline-v5-meta-v1')).match('/offline-v5/.runtime-meta.json')
    return await response!.json()
  })
  expect(after.enabled).toBe(true)
  expect(after.shell_generations).toEqual(previous)
  originUnavailable = true
  await context.setOffline(true)
  const response = await page.goto(origin + '/dashboard/tasks', { waitUntil: 'commit' })
  expect(response?.headers()['x-clarin-offline-route']).toBe('tasks')
})
