import { test, expect } from '@playwright/test'
import { createServer, type Server } from 'node:http'
import { readFile, mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { resolve, sep } from 'node:path'
import { createRequire } from 'node:module'

// Executes the actual compiled public CSR assets and the actual SW route. The
// server below is test infrastructure, not a mock for authorization or sync.
// These shell tests complement, but do not replace, v4 grant and sync E2E.
const projectRoot = resolve(__dirname, '..')
const publicRoot = resolve(projectRoot, 'frontend/public')
const requireFrontend = createRequire(resolve(projectRoot, 'frontend/package.json'))
const { build } = requireFrontend('esbuild') as typeof import('../frontend/node_modules/esbuild')
let server: Server
let origin: string
let workerSource: string
let cookieSeen = false
let cloudflareFailure = false
let cloudflareChallenge = false
let trustedAuthDenial = 0
let originUnavailable = false
let corruptManifest = false
const privateSentinel = 'PRIVATE_TEST_DATA_NEVER_CACHE_V4_918372'

test.beforeAll(async () => {
  const bundled = await build({ entryPoints: [resolve(projectRoot, 'frontend/src/app/sw.js/route.ts')], bundle: true, write: false, platform: 'node', format: 'cjs', tsconfig: resolve(projectRoot, 'frontend/tsconfig.json'), define: { 'process.env.NEXT_PUBLIC_BUILD_VERSION': JSON.stringify('qa-public-shell-v4') } })
  const module = { exports: {} as { GET?: () => Response } }
  new Function('module', 'exports', bundled.outputFiles![0].text)(module, module.exports)
  workerSource = await module.exports.GET!().text()
  server = createServer(async (request, response) => {
    // BrowserContext offline emulation can leave an already-running service
    // worker's network target connected. Refuse the real origin socket too.
    if (originUnavailable) { request.socket.destroy(); return }
    try {
      const url = new URL(request.url || '/', origin || 'http://127.0.0.1')
      if (url.pathname === '/sw.js') {
        response.writeHead(200, { 'Content-Type': 'application/javascript', 'Service-Worker-Allowed': '/', 'Cache-Control': 'no-store' }); response.end(workerSource); return
      }
      if (url.pathname === '/offline-v4/manifest.json') {
        const manifest = JSON.parse(await readFile(resolve(publicRoot, 'offline-v4/manifest.json'), 'utf8'))
        // Only deployment metadata changes for this isolated origin. Asset
        // contents/digests are exactly those generated by the production build.
        manifest.app_origin = origin; manifest.build_id = 'qa-public-shell-v4'
        if (corruptManifest) manifest.assets[0].sha256 = '0'.repeat(64)
        response.writeHead(200, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' }); response.end(JSON.stringify(manifest)); return
      }
      if (url.pathname.startsWith('/api/')) {
        response.writeHead(200, { 'Content-Type': 'application/json', 'X-Clarin-Response': '1', 'Cache-Control': 'no-store' }); response.end(JSON.stringify({ fixture: privateSentinel })); return
      }
      if (url.pathname === '/offline') {
        response.writeHead(200, { 'Content-Type': 'text/html' }); response.end('<!doctype html><html><body><h1>Legacy public fallback</h1></body></html>'); return
      }
      if (url.pathname.startsWith('/offline-v4/') || url.pathname.startsWith('/icons/') || url.pathname === '/favicon.svg') {
        const path = resolve(publicRoot, '.' + url.pathname)
        if (!path.startsWith(publicRoot + sep)) { response.writeHead(404).end(); return }
        const raw = await readFile(path)
        const contentType = path.endsWith('.js') ? 'application/javascript' : path.endsWith('.css') ? 'text/css' : path.endsWith('.html') ? 'text/html' : path.endsWith('.svg') ? 'image/svg+xml' : 'image/png'
        response.writeHead(200, { 'Content-Type': contentType, 'Content-Length': raw.length }); response.end(raw); return
      }
      if (cloudflareFailure) {
        response.writeHead(503, { 'Content-Type': 'text/html' }); response.end('<h1>Cloudflare fixture unavailable</h1>'); return
      }
      if (cloudflareChallenge) {
        response.writeHead(403, { 'Content-Type': 'text/html', 'CF-Mitigated': 'challenge' }); response.end('<h1>Cloudflare challenge fixture</h1>'); return
      }
      if (trustedAuthDenial) {
        response.writeHead(trustedAuthDenial, { 'Content-Type': 'application/json', 'X-Clarin-Response': '1', 'Cache-Control': 'no-store' }); response.end(JSON.stringify({error:'permission_denied'})); return
      }
      cookieSeen = cookieSeen || (request.headers.cookie || '').includes('qa_navigation=preserve')
      response.writeHead(200, { 'Content-Type': 'text/html', 'Cache-Control': 'private, no-store' })
      response.end(`<!doctype html><html><body><h1>Online fixture</h1><p>${privateSentinel}</p></body></html>`)
    } catch {
      response.writeHead(404).end('Not found')
    }
  })
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve))
  const address = server.address(); if (!address || typeof address === 'string') throw new Error('Test server unavailable')
  origin = `http://127.0.0.1:${address.port}`
})

test.afterAll(async () => { await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve())) })
test.beforeEach(() => { cloudflareFailure = false; cloudflareChallenge = false; trustedAuthDenial = 0; originUnavailable = false; cookieSeen = false; corruptManifest = false })

async function prepareWorker(page: import('@playwright/test').Page) {
  await page.goto(origin)
  await page.evaluate(async () => {
    await navigator.serviceWorker.register('/sw.js', { scope: '/' })
    await navigator.serviceWorker.ready
  })
  await page.reload()
  await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true)
  await page.evaluate(() => navigator.serviceWorker.controller!.postMessage({ type: 'CLARIN_OFFLINE_V4_SET_ENABLED', enabled: true }))
  await expect.poll(() => page.evaluate(async () => {
    for (const name of await caches.keys()) {
      const cached = await (await caches.open(name)).match('/offline-v4/.runtime-meta.json')
      if (cached && (await cached.json()).enabled === true) return true
    }
    return false
  }), { timeout: 60_000 }).toBe(true)
}

async function workerMessage(page: import('@playwright/test').Page, message: Record<string, unknown>) {
  return page.evaluate(data => new Promise(resolve => {
    const channel = new MessageChannel()
    channel.port1.onmessage = event => { channel.port1.close(); resolve(event.data) }
    navigator.serviceWorker.controller!.postMessage(data, [channel.port2])
  }), message)
}

test('unprepared browsers do not download the offline runtime or whiteboard bundle', async ({ page }) => {
  const runtimeRequests: string[] = []
  page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/offline-v4/')) runtimeRequests.push(request.url()) })
  await page.goto(origin)
  await page.evaluate(async () => {
    await navigator.serviceWorker.register('/sw.js', { scope: '/' })
    await navigator.serviceWorker.ready
  })
  await page.reload()
  await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true)
  const shells = await page.evaluate(async () => (await caches.keys()).filter(name => name.startsWith('clarin-offline-v4-shell-')))
  expect(shells).toEqual([])
  expect(runtimeRequests).toEqual([])
})

test('ordinary navigation preserves cookies and never caches account HTML or API data', async ({ page, context }) => {
  await prepareWorker(page)
  await context.addCookies([{ name: 'qa_navigation', value: 'preserve', url: origin }])
  cookieSeen = false
  await page.goto(origin + '/dashboard/tasks')
  await expect(page.getByRole('heading', { name: 'Online fixture' })).toBeVisible()
  expect(cookieSeen).toBe(true)
  await page.evaluate(() => fetch('/api/private-test').then(response => response.json()))
  const leaked = await page.evaluate(async sentinel => {
    const found: string[] = []
    for (const name of await caches.keys()) {
      const cache = await caches.open(name)
      for (const request of await cache.keys()) {
        if (new URL(request.url).pathname.startsWith('/api/')) found.push('api cache')
        const response = await cache.match(request)
        if (response && (await response.text()).includes(sentinel)) found.push(request.url)
      }
    }
    return found
  }, privateSentinel)
  expect(leaked).toEqual([])
})

test('prepared normal URLs load the real CSR shell with no network and no private cached fallback', async ({ page, context }) => {
  await prepareWorker(page)
  originUnavailable = true
  await context.setOffline(true)
  for (const path of ['/', '/dashboard/tasks', '/dashboard/contacts', '/dashboard/programs']) {
    await page.goto(origin + path)
    await expect(page.locator('#clarin-offline-root'), `offline shell at ${path}`).toBeVisible()
    await expect(page.locator('body')).not.toContainText(privateSentinel)
    await expect(page.locator('body')).not.toContainText('Legacy public fallback')
  }
  const privateRequest = await page.evaluate(async () => { try { await fetch('/api/private-test'); return 'unexpected response' } catch { return 'unavailable' } })
  expect(privateRequest).toBe('unavailable')
})

test('Cloudflare HTML outage falls back to public offline entry rather than authenticated content', async ({ page }) => {
  await prepareWorker(page)
  cloudflareFailure = true
  await page.goto(origin + '/dashboard')
  await expect(page.locator('#clarin-offline-root')).toBeVisible()
  await expect(page.locator('body')).not.toContainText('Online fixture')
  await expect(page.locator('body')).not.toContainText(privateSentinel)
})

test('the public shell survives a complete browser-process close and offline reopen', async ({ playwright }, testInfo) => {
  const profile = await mkdtemp(resolve(tmpdir(), 'clarin-offline-v4-shell-'))
  const launchOptions = testInfo.project.use.launchOptions || {}
  let persistent = await playwright.chromium.launchPersistentContext(profile, { ...launchOptions, headless: true })
  try {
    await prepareWorker(persistent.pages()[0] || await persistent.newPage())
    await persistent.close()
    originUnavailable = true
    persistent = await playwright.chromium.launchPersistentContext(profile, { ...launchOptions, headless: true })
    const reopened = persistent.pages()[0] || await persistent.newPage()
    await reopened.goto(origin + '/dashboard/tasks')
    await expect(reopened.locator('#clarin-offline-root')).toBeVisible()
    await expect(reopened.locator('body')).not.toContainText(privateSentinel)
    await expect(reopened.locator('[data-mode="offline"]')).toHaveCount(0)
  } finally {
    originUnavailable = false
    await persistent.close()
    // This exact temporary, synthetic profile is owned by this test.
    await rm(profile, { recursive: true, force: true })
  }
})

test('Cloudflare challenge permits public offline entry without granting a local session', async ({ page }) => {
  await prepareWorker(page)
  cloudflareChallenge = true
  await page.goto(origin + '/dashboard/tasks')
  await expect(page.locator('#clarin-offline-root')).toBeVisible()
  await expect(page.locator('body')).not.toContainText('Cloudflare challenge fixture')
  await expect(page.locator('[data-mode="offline"]')).toHaveCount(0)
})

for (const denialStatus of [403, 429]) test(`a trusted Clarin ${denialStatus} denial is not changed into an offline authorization`, async ({ page }) => {
  await prepareWorker(page)
  trustedAuthDenial = denialStatus
  const response = await page.goto(origin + '/dashboard/tasks')
  expect(response?.status()).toBe(denialStatus)
  await expect(page.locator('body')).toContainText('permission_denied')
  await expect(page.locator('#clarin-offline-root')).toHaveCount(0)
})

test('offline mode survives reconnection, reload and another tab without resuming an older online cookie', async ({ page, context }) => {
  await prepareWorker(page)
  await context.addCookies([{ name:'qa_navigation',value:'preserve',url:origin }])
  expect(await workerMessage(page, {type:'CLARIN_OFFLINE_V4_SET_MODE',mode:'offline'})).toMatchObject({ok:true})
  cookieSeen = false
  // Origin is healthy throughout this test. The stale cookie must not select
  // the actor merely because the browser reloads or opens an unsupported URL.
  for (const path of ['/dashboard/tasks','/dashboard/chats','/login']) {
    await page.goto(origin+path)
    await expect(page.locator('#clarin-offline-root')).toBeVisible()
    await expect(page.locator('body')).not.toContainText(privateSentinel)
  }
  await page.reload()
  await expect(page.locator('#clarin-offline-root')).toBeVisible()
  const otherTab = await context.newPage()
  await otherTab.goto(origin+'/dashboard')
  await expect(otherTab.locator('#clarin-offline-root')).toBeVisible()
  await otherTab.close()
  expect(cookieSeen).toBe(false)
  expect(await workerMessage(page, {type:'CLARIN_OFFLINE_V4_SET_MODE',mode:'online'})).toMatchObject({ok:false})
  expect(await workerMessage(page, {type:'CLARIN_OFFLINE_V4_BEGIN_ONLINE_REAUTH'})).toMatchObject({ok:true})
  await page.goto(origin+'/login?offline_reauth=1')
  await expect(page.getByRole('heading',{name:'Online fixture'})).toBeVisible()
  await page.goto(origin+'/dashboard/tasks')
  await expect(page.locator('#clarin-offline-root')).toBeVisible()
  // The real login handler separately enforces password/Turnstile and exact
  // actor/account before its UI is permitted to send this completion message.
  expect(await workerMessage(page, {type:'CLARIN_OFFLINE_V4_SET_MODE',mode:'online'})).toMatchObject({ok:true})
  await page.goto(origin+'/dashboard/tasks')
  await expect(page.getByRole('heading',{name:'Online fixture'})).toBeVisible()
})

test('an update with a corrupt asset cannot replace the last verified offline shell', async ({ page, context }) => {
  await prepareWorker(page)
  const previous = await page.evaluate(async () => {
    const response = await (await caches.open('clarin-offline-v4-meta-v1')).match('/offline-v4/.runtime-meta.json')
    return (await response!.json()).shell_generations
  })
  corruptManifest = true
  const update = await page.evaluate(() => new Promise(resolve => {
    const channel = new MessageChannel()
    channel.port1.onmessage = event => { channel.port1.close(); resolve(event.data) }
    navigator.serviceWorker.controller!.postMessage({type:'CLARIN_OFFLINE_V4_SET_ENABLED', enabled:true},[channel.port2])
  }))
  expect(update).toMatchObject({ok:false,error:'offline_shell_unavailable'})
  const after = await page.evaluate(async () => {
    const response = await (await caches.open('clarin-offline-v4-meta-v1')).match('/offline-v4/.runtime-meta.json')
    return await response!.json()
  })
  expect(after.enabled).toBe(true)
  expect(after.shell_generations).toEqual(previous)
  originUnavailable = true
  await context.setOffline(true)
  await page.goto(origin+'/dashboard/tasks')
  await expect(page.locator('#clarin-offline-root')).toBeVisible()
})

test('actual whiteboard renderer and fonts work entirely from the verified public cache', async ({ page, context }) => {
  await prepareWorker(page)
  const manifest = JSON.parse(await readFile(resolve(publicRoot, 'offline-v4/manifest.json'), 'utf8'))
  const rendererAsset = manifest.assets.find((asset: { url: string }) => /\/chunk-whiteboardRender-[^/]+\.js$/.test(asset.url))
  expect(rendererAsset, 'lazy production whiteboard renderer must be included in integrity manifest').toBeTruthy()
  originUnavailable = true
  await context.setOffline(true)
  const unexpected: string[] = []
  page.on('request', request => { if (!request.url().startsWith(origin + '/offline-v4/') && !request.url().startsWith('data:') && !request.url().startsWith('blob:')) unexpected.push(request.url()) })
  const rendered = await page.evaluate(async modulePath => {
    const { renderOfflineWhiteboard } = await import(modulePath)
    const pixel = document.createElement('canvas'); pixel.width = 2; pixel.height = 2
    const painter = pixel.getContext('2d')!; painter.fillStyle = '#059669'; painter.fillRect(0, 0, 2, 2)
    const base64 = pixel.toDataURL('image/png').split(',')[1]
    const bytes = Uint8Array.from(atob(base64), value => value.charCodeAt(0))
    const digest = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)), value => value.toString(16).padStart(2, '0')).join('')
    const blob = await renderOfflineWhiteboard({ id: 'fixture', name: 'QA pizarra', version: 1, updated_at: '2026-09-14', editor_version: '0.18.1-clarin.6', assets: [{ file_id: 'fixture-image', content_type: 'image/png', content_hash: digest, data_base64: base64, size_bytes: bytes.length }], scene: { elements: [
      { id: 'rect', type: 'rectangle', x: 0, y: 0, width: 200, height: 100, angle: 0, strokeColor: '#1e293b', backgroundColor: '#d1fae5', fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid', roughness: 1, opacity: 100, groupIds: [], frameId: null, roundness: null, seed: 3, version: 1, versionNonce: 4, isDeleted: false, boundElements: [], updated: 1, link: null, locked: false },
      { id: 'text', type: 'text', x: 10, y: 20, width: 150, height: 25, angle: 0, strokeColor: '#1e293b', backgroundColor: 'transparent', fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid', roughness: 0, opacity: 100, groupIds: [], frameId: null, roundness: null, seed: 5, version: 1, versionNonce: 6, isDeleted: false, boundElements: [], updated: 1, link: null, locked: false, fontSize: 20, fontFamily: 5, text: 'Clarín sin conexión', originalText: 'Clarín sin conexión', textAlign: 'left', verticalAlign: 'top', containerId: null, autoResize: true, lineHeight: 1.25 },
      { id: 'image', type: 'image', fileId: 'fixture-image', status: 'saved', scale: [1, 1], x: 10, y: 110, width: 30, height: 30, angle: 0, strokeColor: 'transparent', backgroundColor: 'transparent', fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid', roughness: 0, opacity: 100, groupIds: [], frameId: null, roundness: null, seed: 7, version: 1, versionNonce: 8, isDeleted: false, boundElements: [], updated: 1, link: null, locked: false },
    ], appState: { viewBackgroundColor: '#ffffff' } } }, new AbortController().signal)
    const text = await blob.text()
    const image = new Image(); const url = URL.createObjectURL(blob)
    image.src = url; await image.decode(); const dimensions = { width: image.naturalWidth, height: image.naturalHeight }; URL.revokeObjectURL(url)
    return { bytes: blob.size, type: blob.type, fontEmbedded: /data:(?:font|application)\//.test(text), imageEmbedded: text.includes('data:image/png;base64,'), hasText: text.includes('Clarín sin conexión'), ...dimensions }
  }, origin + rendererAsset.url)
  expect(rendered.bytes).toBeGreaterThan(500)
  expect(rendered.type).toBe('image/svg+xml')
  expect(rendered.hasText).toBe(true)
  expect(rendered.fontEmbedded).toBe(true)
  expect(rendered.imageEmbedded).toBe(true)
  expect(rendered.width).toBeGreaterThan(0)
  expect(rendered.height).toBeGreaterThan(0)
  expect(unexpected).toEqual([])
})
