import { createServer } from 'node:http'
import { spawn } from 'node:child_process'
import { createInterface } from 'node:readline'
import { mkdir, writeFile, stat, rm } from 'node:fs/promises'
import { timingSafeEqual } from 'node:crypto'
import path from 'node:path'

const PORT = Number(process.env.PORT || 8787)
const CODEX_HOME = process.env.CODEX_HOME || '/var/lib/codex'
const BRIDGE_TOKEN = process.env.EROS_CODEX_BRIDGE_TOKEN || ''
const MCP_BASE_URL = trimRight(process.env.EROS_MCP_BASE_URL || 'http://clarin-backend:8081/mcp', '/')
const MCP_TOKEN = process.env.EROS_MCP_ACCESS_TOKEN || ''
const CODEX_MODEL = process.env.EROS_CODEX_MODEL || ''
const CODEX_REASONING_EFFORT = process.env.EROS_CODEX_REASONING_EFFORT || ''
const REQUEST_TIMEOUT_MS = Number(process.env.EROS_CODEX_REQUEST_TIMEOUT_MS || 120000)
const DEVICE_LOGIN_TTL_MS = Number(process.env.EROS_DEVICE_LOGIN_TTL_MS || 15 * 60 * 1000)
const AUTH_VALIDATION_INTERVAL_MS = Number(process.env.EROS_AUTH_VALIDATION_INTERVAL_MS || 5 * 60 * 1000)
const CODEX_BIN = process.env.CODEX_BIN || 'codex'
const WORKDIR = process.env.EROS_CODEX_WORKDIR || '/tmp/eros-codex-workspace'
const MCP_SERVER_NAME = process.env.EROS_MCP_SERVER_NAME || 'clarin'

let prepared = false

function trimRight(value, suffix) {
  let out = String(value || '')
  while (out.endsWith(suffix)) out = out.slice(0, -suffix.length)
  return out
}

function tomlString(value) {
  return JSON.stringify(String(value || ''))
}

function hasBridgeAccess(req) {
  if (!BRIDGE_TOKEN) return false
  const raw = req.headers.authorization || ''
  if (!raw.toLowerCase().startsWith('bearer ')) return false
  const provided = Buffer.from(raw.slice(7).trim())
  const expected = Buffer.from(BRIDGE_TOKEN)
  return provided.length === expected.length && timingSafeEqual(provided, expected)
}

function redactError(err) {
  const raw = err && err.message ? err.message : String(err)
  return [BRIDGE_TOKEN, MCP_TOKEN].reduce((text, secret) => {
    if (!secret) return text
    return text.replaceAll(secret, '[redacted]')
  }, raw)
}

async function exists(filePath) {
  try {
    const info = await stat(filePath)
    return info.isFile()
  } catch {
    return false
  }
}

async function prepareCodexHome() {
  if (prepared) return
  await mkdir(CODEX_HOME, { recursive: true, mode: 0o700 })
  await mkdir(WORKDIR, { recursive: true, mode: 0o700 })
  await purgeCodexAppsCache()

  const config = [
    '# Generated by clarin-codex-bridge. Do not store secrets here.',
    'forced_login_method = "chatgpt"',
    'approval_policy = "never"',
    'sandbox_mode = "read-only"',
    CODEX_MODEL ? `model = ${tomlString(CODEX_MODEL)}` : '',
    CODEX_REASONING_EFFORT ? `model_reasoning_effort = ${tomlString(CODEX_REASONING_EFFORT)}` : '',
    '',
    '[apps._default]',
    'enabled = false',
    'destructive_enabled = false',
    'open_world_enabled = false',
    'approvals_reviewer = "auto_review"',
    'default_tools_approval_mode = "approve"',
    '',
    `[mcp_servers.${MCP_SERVER_NAME}]`,
    `url = ${tomlString(MCP_BASE_URL)}`,
    'bearer_token_env_var = "EROS_MCP_ACCESS_TOKEN"',
    'enabled = true',
    'required = true',
    'default_tools_approval_mode = "approve"',
    'startup_timeout_sec = 20',
    'tool_timeout_sec = 90',
    ''
  ].filter(Boolean).join('\n')
  await writeFile(path.join(CODEX_HOME, 'config.toml'), config, { mode: 0o600 })

  prepared = true
}

async function purgeCodexAppsCache() {
  const cacheDir = path.join(CODEX_HOME, 'cache')
  await Promise.all([
    rm(path.join(cacheDir, 'codex_apps_tools'), { recursive: true, force: true }),
    rm(path.join(cacheDir, 'codex_apps_server_info'), { recursive: true, force: true })
  ])
}

function codexAuthIssueFromText(value) {
  const text = String(value || '').toLowerCase()
  if (!text) return null
  if (
    text.includes('token_revoked') ||
    text.includes('token_invalidated') ||
    text.includes('token has been invalidated') ||
    text.includes('invalidated oauth token') ||
    (text.includes('401 unauthorized') && text.includes('chatgpt.com/backend-api')) ||
    (text.includes('failed to refresh available models') && text.includes('401'))
  ) {
    return {
      code: 'codex_auth_revoked',
      message: 'The OpenAI connection used by Eros must be renewed.',
      detected_at: new Date().toISOString()
    }
  }
  return null
}

class CodexAuthError extends Error {
  constructor(issue) {
    super(issue?.message || 'Codex ChatGPT auth is not valid.')
    this.name = 'CodexAuthError'
    this.code = issue?.code || 'codex_auth_invalid'
    this.detail = issue?.message || ''
  }
}

function isCodexAuthError(err) {
  return err instanceof CodexAuthError || String(err?.code || '') === 'codex_auth_revoked'
}

function emptyDeviceLoginState() {
  return {
    status: 'idle',
    login_id: '',
    verification_url: '',
    user_code: '',
    started_at: null,
    completed_at: null,
    error: null
  }
}

function publicDeviceLoginState(state) {
  const status = String(state?.status || 'idle')
  return {
    status,
    login_id: state?.login_id || '',
    verification_url: status === 'pending' ? state?.verification_url || '' : '',
    user_code: status === 'pending' ? state?.user_code || '' : '',
    started_at: state?.started_at || null,
    completed_at: state?.completed_at || null,
    error: state?.error || null
  }
}

function normalizeAccountStatus(result) {
  const account = result?.account && typeof result.account === 'object' ? result.account : null
  const authMode = account?.type === 'apiKey' ? 'api_key' : account?.type || null
  return {
    authenticated: Boolean(account),
    requires_openai_auth: result?.requiresOpenaiAuth !== false,
    auth_mode: authMode,
    email: account?.type === 'chatgpt' ? String(account.email || '').slice(0, 320) : '',
    plan_type: account?.type === 'chatgpt' ? String(account.planType || '').slice(0, 80) : ''
  }
}

function safeAuthError(value) {
  const text = String(value || '').toLowerCase()
  if (text.includes('expired')) return 'El código venció. Genera uno nuevo para continuar.'
  if (text.includes('denied') || text.includes('declined') || text.includes('cancel')) {
    return 'La conexión fue cancelada antes de completarse.'
  }
  return 'No se pudo completar la conexión con OpenAI.'
}

function trustedVerificationURL(value) {
  try {
    const url = new URL(String(value || ''))
    if (url.protocol !== 'https:' || !['auth.openai.com', 'chatgpt.com'].includes(url.hostname)) return ''
    return url.toString()
  } catch {
    return ''
  }
}

function safeDeviceCode(value) {
  const code = String(value || '').trim()
  return /^[a-z0-9-]{4,64}$/i.test(code) ? code : ''
}

function codexEnv() {
  return {
    ...process.env,
    CODEX_HOME,
    EROS_MCP_ACCESS_TOKEN: MCP_TOKEN || process.env.EROS_MCP_ACCESS_TOKEN || '',
    HOME: process.env.HOME || '/tmp'
  }
}

class CodexAppServer {
  constructor() {
    this.proc = null
    this.ready = null
    this.initialized = false
    this.nextId = 1
    this.pending = new Map()
    this.turns = new Map()
    this.stderrTail = []
    this.deviceLogin = emptyDeviceLoginState()
    this.deviceLoginPromise = null
    this.loginCompletions = new Map()
    this.account = null
    this.authIssue = null
    this.lastAuthValidationAt = 0
  }

  async ensureStarted() {
    if (this.ready) return this.ready
    this.ready = this.start()
    return this.ready
  }

  async start() {
    await prepareCodexHome()
    this.authIssue = null
    const child = spawn(CODEX_BIN, ['app-server', '--stdio'], {
      cwd: WORKDIR,
      env: codexEnv(),
      stdio: ['pipe', 'pipe', 'pipe']
    })
    this.proc = child

    child.on('exit', (code, signal) => {
      if (this.proc !== child) return
      this.initialized = false
      this.ready = null
      this.failPendingDeviceLogin('La conexión se interrumpió antes de completarse.')
      const err = new Error(`codex app-server exited code=${code} signal=${signal}`)
      for (const { reject } of this.pending.values()) reject(err)
      for (const active of this.turns.values()) active.reject(err)
      this.pending.clear()
      this.turns.clear()
    })
    child.on('error', err => {
      if (this.proc !== child) return
      this.initialized = false
      this.ready = null
      this.failPendingDeviceLogin('No se pudo mantener el servicio de conexión.')
      for (const { reject } of this.pending.values()) reject(err)
      this.pending.clear()
    })

    const rl = createInterface({ input: child.stdout })
    rl.on('line', line => this.handleLine(line))
    child.stderr.on('data', chunk => {
      const text = redactError(chunk.toString('utf8')).trim()
      if (!text) return
      this.stderrTail.push(text)
      if (this.stderrTail.length > 20) this.stderrTail.shift()
      const authIssue = codexAuthIssueFromText(text)
      if (authIssue) this.authIssue = authIssue
      console.error(`[codex] ${text}`)
    })

    await this.request('initialize', {
      clientInfo: { name: 'clarin-eros-bridge', title: 'Clarin Eros Bridge', version: '1.0.0' },
      capabilities: { experimentalApi: true, requestAttestation: false, optOutNotificationMethods: null }
    }, 30000)
    this.notify('initialized')
    this.initialized = true
    await this.enforceErosIsolation()
  }

  handleLine(line) {
    if (!line.trim()) return
    let msg
    try {
      msg = JSON.parse(line)
    } catch (err) {
      console.error(`[codex] invalid json: ${redactError(err)}`)
      return
    }

    if (Object.prototype.hasOwnProperty.call(msg, 'id') && (Object.prototype.hasOwnProperty.call(msg, 'result') || Object.prototype.hasOwnProperty.call(msg, 'error'))) {
      const pending = this.pending.get(msg.id)
      if (!pending) return
      this.pending.delete(msg.id)
      clearTimeout(pending.timer)
      if (msg.error) pending.reject(new Error(msg.error.message || JSON.stringify(msg.error)))
      else pending.resolve(msg.result)
      return
    }

    if (Object.prototype.hasOwnProperty.call(msg, 'id') && msg.method) {
      this.handleServerRequest(msg)
      return
    }

    if (msg.method) {
      this.handleNotification(msg)
    }
  }

  handleServerRequest(msg) {
    const deny = reason => this.respondError(msg.id, -32010, reason)
    switch (msg.method) {
      case 'item/commandExecution/requestApproval':
        this.respond(msg.id, { decision: 'decline' })
        break
      case 'item/fileChange/requestApproval':
        this.respond(msg.id, { decision: 'decline' })
        break
      case 'execCommandApproval':
      case 'applyPatchApproval':
        this.respond(msg.id, { decision: 'denied' })
        break
      case 'item/permissions/requestApproval':
        this.respond(msg.id, { permissions: {}, scope: 'turn', strictAutoReview: true })
        break
      case 'mcpServer/elicitation/request':
        this.respond(msg.id, { action: 'decline', content: null, _meta: null })
        break
      case 'item/tool/requestUserInput':
        this.respond(msg.id, { answers: {} })
        break
      case 'item/tool/call':
        this.respond(msg.id, {
          success: false,
          contentItems: [{ type: 'inputText', text: 'Dynamic tools are disabled for Eros. Use the Clarin MCP tools only.' }]
        })
        break
      case 'attestation/generate':
        deny('Attestation is not supported by Clarin Eros bridge.')
        break
      default:
        deny(`Unsupported server request: ${msg.method}`)
    }
  }

  handleNotification(msg) {
    const params = msg.params || {}
    if (msg.method === 'account/login/completed') {
      this.completeDeviceLogin(params)
      return
    }
    if (msg.method === 'account/updated') {
      this.account = {
        ...(this.account || normalizeAccountStatus(null)),
        authenticated: Boolean(params.authMode),
        auth_mode: params.authMode || null,
        plan_type: params.planType || null,
        requires_openai_auth: true
      }
      return
    }
    if (msg.method === 'turn/completed') {
      const turn = params.turn
      const active = turn && this.turns.get(turn.id)
      if (active) {
        const completedTurn = hydrateCompletedTurn(turn, active)
        this.turns.delete(turn.id)
        active.resolve(completedTurn)
      }
      return
    }
    if (msg.method === 'error') {
      const turnId = params.turnId
      const active = turnId && this.turns.get(turnId)
      if (active) {
        this.turns.delete(turnId)
        active.reject(new Error(params.error?.message || 'Codex turn failed'))
      }
      return
    }
    if (msg.method === 'item/completed') {
      const active = params.turnId && this.turns.get(params.turnId)
      if (active && params.item) active.items.push(params.item)
      return
    }
    if (msg.method === 'item/agentMessage/delta') {
      const active = params.turnId && this.turns.get(params.turnId)
      if (active && params.delta) active.deltas.push(params.delta)
    }
  }

  request(method, params, timeoutMs = REQUEST_TIMEOUT_MS) {
    if (!this.proc || !this.proc.stdin.writable) {
      return Promise.reject(new Error('codex app-server is not running'))
    }
    const id = this.nextId++
    const message = params === undefined ? { method, id } : { method, id, params }
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id)
        reject(new Error(`${method} timed out`))
      }, timeoutMs)
      this.pending.set(id, { resolve, reject, timer })
      this.proc.stdin.write(`${JSON.stringify(message)}\n`)
    })
  }

  notify(method, params) {
    if (!this.proc || !this.proc.stdin.writable) return
    const message = params === undefined ? { method } : { method, params }
    this.proc.stdin.write(`${JSON.stringify(message)}\n`)
  }

  respond(id, result) {
    if (!this.proc || !this.proc.stdin.writable) return
    this.proc.stdin.write(`${JSON.stringify({ id, result })}\n`)
  }

  respondError(id, code, message) {
    if (!this.proc || !this.proc.stdin.writable) return
    this.proc.stdin.write(`${JSON.stringify({ id, error: { code, message } })}\n`)
  }

  async authStatus(refreshToken = false) {
    await this.ensureStarted()
    const result = await this.request('account/read', { refreshToken }, 20000)
    this.account = normalizeAccountStatus(result)
    if (refreshToken) this.lastAuthValidationAt = Date.now()
    if (this.account.authenticated && (refreshToken || !this.authIssue)) this.authIssue = null
    return this.account
  }

  managedAuthNeedsValidation() {
    return Boolean(
      this.authIssue ||
      !this.lastAuthValidationAt ||
      Date.now() - this.lastAuthValidationAt >= AUTH_VALIDATION_INTERVAL_MS
    )
  }

  async recoverManagedAuth() {
    try {
      const account = await this.authStatus(this.managedAuthNeedsValidation())
      if (account.authenticated) {
        this.authIssue = null
        return account
      }
    } catch (err) {
      console.warn(`[eros] OpenAI session refresh failed: ${redactError(err)}`)
      this.authIssue = this.authIssue || codexAuthIssueFromText(err?.message || err) || {
        code: 'codex_auth_required',
        message: 'The OpenAI connection used by Eros must be renewed.',
        detected_at: new Date().toISOString()
      }
    }
    this.authIssue = this.authIssue || {
      code: 'codex_auth_required',
      message: 'Eros must be connected to OpenAI before it can answer.',
      detected_at: new Date().toISOString()
    }
    throw new CodexAuthError(this.authIssue)
  }

  async startDeviceLogin() {
    await this.ensureStarted()
    await this.expireDeviceLoginIfNeeded()
    if (this.deviceLogin.status === 'pending') {
      return publicDeviceLoginState(this.deviceLogin)
    }
    if (this.deviceLoginPromise) return this.deviceLoginPromise
    const loginPromise = this.request('account/login/start', { type: 'chatgptDeviceCode' }, 30000)
      .then(result => {
        const verificationURL = trustedVerificationURL(result?.verificationUrl)
        const userCode = safeDeviceCode(result?.userCode)
        if (!result?.loginId || !verificationURL || !userCode) {
          throw new Error('OpenAI did not return a valid device authorization challenge.')
        }
        this.deviceLogin = {
          status: 'pending',
          login_id: result.loginId,
          verification_url: verificationURL,
          user_code: userCode,
          started_at: new Date().toISOString(),
          completed_at: null,
          error: null
        }
        const earlyCompletion = this.loginCompletions.get(result.loginId)
        if (earlyCompletion) {
          this.loginCompletions.delete(result.loginId)
          this.completeDeviceLogin(earlyCompletion)
        }
        return publicDeviceLoginState(this.deviceLogin)
      })
      .finally(() => {
        if (this.deviceLoginPromise === loginPromise) this.deviceLoginPromise = null
      })
    this.deviceLoginPromise = loginPromise
    return loginPromise
  }

  async getConnectionStatus() {
    await this.ensureStarted()
    await this.expireDeviceLoginIfNeeded()
    let account = this.account || normalizeAccountStatus(null)
    try {
      account = await this.authStatus(this.managedAuthNeedsValidation())
    } catch (err) {
      console.warn(`[eros] could not read OpenAI connection status: ${redactError(err)}`)
      this.authIssue = this.authIssue || codexAuthIssueFromText(err?.message || err) || {
        code: 'codex_auth_required',
        message: 'The OpenAI connection used by Eros must be renewed.',
        detected_at: new Date().toISOString()
      }
    }
    return {
      connected: Boolean(account.authenticated && !this.authIssue),
      auth_mode: account.auth_mode,
      email: account.email,
      plan_type: account.plan_type,
      requires_openai_auth: account.requires_openai_auth,
      error: this.authIssue?.code || null,
      login: publicDeviceLoginState(this.deviceLogin)
    }
  }

  async cancelDeviceLogin(loginId = '') {
    await this.ensureStarted()
    if (this.deviceLogin.status !== 'pending') {
      return publicDeviceLoginState(this.deviceLogin)
    }
    if (loginId && loginId !== this.deviceLogin.login_id) {
      throw new Error('The requested OpenAI connection attempt is no longer active.')
    }
    await this.request('account/login/cancel', { loginId: this.deviceLogin.login_id }, 15000)
    this.deviceLogin = {
      ...this.deviceLogin,
      status: 'cancelled',
      verification_url: '',
      user_code: '',
      completed_at: new Date().toISOString(),
      error: null
    }
    return publicDeviceLoginState(this.deviceLogin)
  }

  async logout() {
    await this.ensureStarted()
    if (this.deviceLogin.status === 'pending') {
      await this.cancelDeviceLogin(this.deviceLogin.login_id)
    }
    await this.request('account/logout', undefined, 15000)
    this.account = normalizeAccountStatus(null)
    this.authIssue = null
    this.lastAuthValidationAt = 0
    this.deviceLogin = emptyDeviceLoginState()
    return { connected: false }
  }

  completeDeviceLogin(params) {
    const loginId = String(params?.loginId || '')
    if (!loginId || this.deviceLogin.login_id !== loginId) {
      if (loginId) {
        this.loginCompletions.set(loginId, params)
        while (this.loginCompletions.size > 5) {
          this.loginCompletions.delete(this.loginCompletions.keys().next().value)
        }
      }
      return
    }
    const success = Boolean(params.success)
    this.deviceLogin = {
      ...this.deviceLogin,
      status: success ? 'completed' : 'failed',
      verification_url: '',
      user_code: '',
      completed_at: new Date().toISOString(),
      error: success ? null : safeAuthError(params.error)
    }
    if (success) {
      this.authIssue = null
      this.lastAuthValidationAt = 0
    }
  }

  async expireDeviceLoginIfNeeded() {
    if (this.deviceLogin.status !== 'pending' || !this.deviceLogin.started_at) return
    const startedAt = new Date(this.deviceLogin.started_at).getTime()
    if (!Number.isFinite(startedAt) || Date.now() - startedAt < DEVICE_LOGIN_TTL_MS) return
    try {
      await this.request('account/login/cancel', { loginId: this.deviceLogin.login_id }, 10000)
    } catch {
      // The authorization server may already have expired the attempt.
    }
    this.deviceLogin = {
      ...this.deviceLogin,
      status: 'failed',
      verification_url: '',
      user_code: '',
      completed_at: new Date().toISOString(),
      error: 'El código venció. Genera uno nuevo para continuar.'
    }
  }

  failPendingDeviceLogin(message) {
    if (this.deviceLogin.status !== 'pending') return
    this.deviceLogin = {
      ...this.deviceLogin,
      status: 'failed',
      verification_url: '',
      user_code: '',
      completed_at: new Date().toISOString(),
      error: message
    }
  }

  async mcpStatus() {
    await this.ensureStarted()
    return this.request('mcpServerStatus/list', { limit: 20, detail: 'toolsAndAuthOnly' }, 20000)
  }

  async chat(payload) {
    return this.chatWithRecovery(payload)
  }

  async chatWithRecovery(payload) {
    let lastErr = null
    let retryPayload = payload
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        const result = await this.chatOnce(retryPayload)
        result.metadata = {
          ...(result.metadata || {}),
          attempts: attempt + 1,
          recovered: attempt > 0
        }
        return result
      } catch (err) {
        lastErr = err
        if (attempt > 0) break
        if (isRecoverableToolAuthError(err)) {
          console.warn(`[eros] recovering Codex bridge after tool auth/isolation issue: ${redactError(err)}`)
          retryPayload = { ...payload, codex_thread_id: '' }
          await this.restart({ purgeApps: true })
          continue
        }
        if (!isCodexAuthError(err) && isRecoverableCodexAuthError(err)) {
          console.warn(`[eros] refreshing the managed OpenAI session after an auth issue: ${redactError(err)}`)
          try {
            const account = await this.authStatus(true)
            if (account.authenticated) continue
          } catch (refreshErr) {
            console.warn(`[eros] managed OpenAI session refresh failed: ${redactError(refreshErr)}`)
          }
          this.authIssue = codexAuthIssueFromText(err?.message || err) || {
            code: 'codex_auth_required',
            message: 'The OpenAI connection used by Eros must be renewed.',
            detected_at: new Date().toISOString()
          }
        }
        break
      }
    }
    throw lastErr
  }

  async chatOnce(payload) {
    const requestStartedAt = Date.now()
    await this.ensureStarted()
    const account = await this.recoverManagedAuth()
    if (!account.authenticated) {
      throw new CodexAuthError({
        code: 'codex_auth_required',
        message: 'Eros must be connected to OpenAI before it can answer.'
      })
    }
    const requestedMcp = trimRight(payload.mcp_base_url || '', '/')
    if (requestedMcp && requestedMcp !== MCP_BASE_URL) {
      throw new Error('bridge MCP URL does not match configured EROS_MCP_BASE_URL')
    }
    const codexModel = effectiveCodexModel(payload.codex_model)
    const reasoningEffort = effectiveReasoningEffort(payload.reasoning_effort)
    const instructions = buildInstructions(payload)
    let threadId = payload.codex_thread_id || ''
    let resumed = false
    if (threadId) {
      try {
        await this.request('thread/resume', this.resumeThreadParams(threadId, instructions, codexModel), 30000)
        resumed = true
      } catch (err) {
        console.warn(`[eros] could not resume Codex thread; starting a new one: ${redactError(err)}`)
        threadId = ''
      }
    }
    if (!threadId) {
      const started = await this.request('thread/start', this.startThreadParams(instructions, codexModel), 30000)
      threadId = started.thread.id
    }

    const inputText = buildTurnInput(payload, !resumed)
    const turnStartedAt = Date.now()
    const startedTurn = await this.request('turn/start', {
      threadId,
      input: [{ type: 'text', text: inputText, text_elements: [] }],
      approvalPolicy: 'never',
      approvalsReviewer: 'auto_review',
      sandboxPolicy: { type: 'readOnly', networkAccess: true },
      ...(codexModel ? { model: codexModel } : {}),
      ...(reasoningEffort ? { effort: reasoningEffort } : {})
    }, 30000)
    const turnId = startedTurn.turn.id
    const turn = await this.waitForTurn(turnId, REQUEST_TIMEOUT_MS)
    if (turn.status === 'failed') {
      throw new Error(`Codex turn failed: ${summarizeTurnError(turn)}`)
    }
    const response = extractAssistantText(turn)
    const toolCalls = extractMcpTools(turn)
    const fileExports = extractErosFileExports(turn)
    const externalCalls = toolCalls.filter(call => call.server && call.server !== MCP_SERVER_NAME)
    if (externalCalls.length > 0) {
      throw new RecoverableToolAuthError(`Codex attempted external MCP server(s): ${externalCalls.map(call => call.server).join(',')}`)
    }
    if (!response) {
      console.warn(`[eros] Codex completed without assistant response: ${summarizeTurnForLog(turn)}`)
      throw new Error('Codex completed without a final assistant response')
    }
    if (looksLikeReauthenticationResponse(response)) {
      throw new RecoverableToolAuthError('Codex returned a tool reauthentication response')
    }
    return {
      success: true,
      response,
      codex_thread_id: threadId,
      status: turn.status || 'completed',
      tool_calls: toolCalls,
      file_exports: fileExports,
      metadata: {
        mcp_server: MCP_SERVER_NAME,
        model: codexModel,
        reasoning_effort: reasoningEffort,
        duration_ms: Date.now() - requestStartedAt,
        turn_duration_ms: Date.now() - turnStartedAt,
        auth_mode: account.auth_mode || null
      }
    }
  }

  startThreadParams(instructions, codexModel) {
    return {
      cwd: WORKDIR,
      approvalPolicy: 'never',
      approvalsReviewer: 'auto_review',
      sandbox: 'read-only',
      serviceName: 'clarin-eros',
      baseInstructions: instructions.base,
      developerInstructions: instructions.developer,
      threadSource: 'clarin-eros-bridge',
      ...(codexModel ? { model: codexModel } : {})
    }
  }

  async enforceErosIsolation() {
    try {
      await this.request('config/batchWrite', {
        edits: [
          { keyPath: 'apps._default.enabled', value: false, mergeStrategy: 'upsert' },
          { keyPath: 'apps._default.destructive_enabled', value: false, mergeStrategy: 'upsert' },
          { keyPath: 'apps._default.open_world_enabled', value: false, mergeStrategy: 'upsert' },
          { keyPath: 'apps._default.approvals_reviewer', value: 'auto_review', mergeStrategy: 'upsert' },
          { keyPath: 'apps._default.default_tools_approval_mode', value: 'approve', mergeStrategy: 'upsert' }
        ]
      }, 15000)
    } catch (err) {
      console.warn(`[eros] could not enforce Codex app isolation via config RPC: ${redactError(err)}`)
    }
  }

  async restart(options = {}) {
    await this.stopProc()
    this.initialized = false
    this.ready = null
    this.pending.clear()
    this.turns.clear()
    if (options.purgeApps) {
      prepared = false
      await purgeCodexAppsCache()
    }
    await this.ensureStarted()
  }

  async stopProc() {
    const child = this.proc
    if (!child || child.exitCode !== null) return
    await new Promise(resolve => {
      const timer = setTimeout(resolve, 2000)
      child.once('exit', () => {
        clearTimeout(timer)
        resolve()
      })
      child.kill('SIGTERM')
    })
  }

  resumeThreadParams(threadId, instructions, codexModel) {
    return {
      threadId,
      cwd: WORKDIR,
      approvalPolicy: 'never',
      approvalsReviewer: 'auto_review',
      sandbox: 'read-only',
      baseInstructions: instructions.base,
      developerInstructions: instructions.developer,
      ...(codexModel ? { model: codexModel } : {})
    }
  }

  waitForTurn(turnId, timeoutMs) {
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.turns.delete(turnId)
        reject(new Error('Codex turn timed out'))
      }, timeoutMs)
      this.turns.set(turnId, {
        items: [],
        deltas: [],
        resolve: turn => {
          clearTimeout(timer)
          resolve(turn)
        },
        reject: err => {
          clearTimeout(timer)
          reject(err)
        }
      })
    })
  }
}

function hydrateCompletedTurn(turn, active) {
  const turnItems = Array.isArray(turn?.items) ? turn.items : []
  const activeItems = Array.isArray(active?.items) ? active.items : []
  const deltas = Array.isArray(active?.deltas) ? active.deltas : []
  return {
    ...turn,
    items: mergeTurnItems(activeItems, turnItems),
    deltas
  }
}

function mergeTurnItems(...groups) {
  const merged = []
  const indexByID = new Map()
  for (const group of groups) {
    if (!Array.isArray(group)) continue
    for (const item of group) {
      if (!item || typeof item !== 'object') continue
      const id = typeof item.id === 'string' && item.id ? item.id : ''
      if (id && indexByID.has(id)) {
        const index = indexByID.get(id)
        merged[index] = { ...merged[index], ...item }
        continue
      }
      if (id) indexByID.set(id, merged.length)
      merged.push(item)
    }
  }
  return merged
}

class RecoverableToolAuthError extends Error {
  constructor(message) {
    super(message)
    this.name = 'RecoverableToolAuthError'
  }
}

function isRecoverableToolAuthError(err) {
  return err instanceof RecoverableToolAuthError
}

function isRecoverableCodexAuthError(err) {
  const text = String(err?.message || err || '').toLowerCase()
  return [
    'requiresopenaiauth',
    'requires openai auth',
    'requires_openai_auth',
    'not authenticated',
    'unauthorized',
    'chatgpt auth',
    'login required',
    'authentication required'
  ].some(marker => text.includes(marker))
}

function looksLikeReauthenticationResponse(text) {
  const normalized = String(text || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
  return [
    'requiere reautenticacion',
    'necesita reautenticacion',
    'volver a vincular',
    'vuelve a vincular',
    'reconectar la cuenta',
    'reconnect the account',
    'reauthentication',
    're-authentication',
    'error temporal de acceso',
    'herramienta mcp de clarin devolvio',
    'no pude contarlo',
    'no puedo contarlo',
    'no pude consultar',
    'no puedo consultar',
    'no puedo acceder a los datos',
    'no pude acceder a los datos'
  ].some(marker => normalized.includes(marker))
}

function effectiveCodexModel(value) {
  const model = String(value || CODEX_MODEL || '').trim()
  return model || ''
}

function effectiveReasoningEffort(value) {
  const effort = String(value || CODEX_REASONING_EFFORT || '').trim().toLowerCase()
  return ['low', 'medium', 'high', 'xhigh'].includes(effort) ? effort : ''
}

function buildInstructions(payload) {
  const accountID = String(payload.account_id || '')
  const global = String(payload.global_instructions || '').trim()
  return {
    base: [
      'Eres Eros, el asistente operativo de Clarin.',
      'Responde en español claro y directo.',
      'Clarin usa cuentas/tenants; nunca digas empresa salvo que cites texto existente.',
      'Contact es la entidad padre; Lead y Chat son hijos paralelos.',
      'No inventes datos de Clarin. Si necesitas datos, usa herramientas MCP.',
      `Usa exclusivamente el servidor MCP "${MCP_SERVER_NAME}" para consultar datos de Clarin.`,
      'No uses apps, conectores ni tools externas de Codex como codex_apps, Google Calendar, Gmail, Drive o similares.',
      `Para toda herramienta MCP que acepte cuenta, usa account_id="${accountID}".`,
      'Nunca consultes ni infieras datos de otra cuenta/tenant.',
      'No ejecutes shell, no leas ni escribas archivos, no modifiques el repositorio y no uses herramientas locales.',
      'Nunca pidas al usuario reautenticar, revincular o reconectar una cuenta externa; si una tool falla por autenticacion, tratalo como error interno transitorio.',
      'Si el usuario pide un archivo, fichero, Excel, CSV, Word, PowerPoint, PDF o descarga, usa las herramientas MCP de Clarin para preparar el adjunto.',
      'Para adjuntos, llama render_file_export con format, filename, title y content completo. No pegues el contenido completo del fichero en tu respuesta final; confirma el adjunto y, como mucho, resume una frase.',
      'No generes base64, no inventes URLs publicas y no digas que se guardo en servidor.',
      'Si una herramienta no existe en MCP, explica la limitacion y sugiere crear una herramienta MCP nueva.',
      'Cuando MCP devuelva datos estructurados, resume y usa tablas compactas si ayuda.'
    ].join('\n'),
    developer: [
      global ? `Instrucciones globales configuradas por Admin:\n${global}` : '',
      `Contexto fijo: account_id=${accountID}, user_id=${payload.user_id || ''}, conversation_id=${payload.conversation_id || ''}.`,
      payload.current_page ? `Pagina actual del usuario: ${payload.current_page}.` : '',
      `Prioridad de seguridad: aislamiento por account_id, no shell, no filesystem, no datos fuera del MCP "${MCP_SERVER_NAME}".`
    ].filter(Boolean).join('\n\n')
  }
}

function buildTurnInput(payload, includeHistory) {
  const parts = []
  if (includeHistory && Array.isArray(payload.history) && payload.history.length) {
    const history = payload.history
      .slice(-20)
      .map(m => `${m.role === 'assistant' ? 'Eros' : 'Usuario'}: ${String(m.content || '').slice(0, 4000)}`)
      .join('\n')
    parts.push(`Historial reciente de la conversacion en Clarin:\n${history}`)
  }
  parts.push(`Mensaje del usuario:\n${payload.message}`)
  return parts.join('\n\n')
}

function extractAssistantText(turn) {
  const items = Array.isArray(turn?.items) ? turn.items : []
  const final = [...items].reverse().find(item => item.type === 'agentMessage' && item.phase === 'final_answer' && item.text)
  if (final) return final.text.trim()
  const any = [...items].reverse().find(item => item.type === 'agentMessage' && item.text)
  if (any) return any.text.trim()
  const deltas = Array.isArray(turn?.deltas) ? turn.deltas : []
  return deltas.join('').trim()
}

function extractMcpTools(turn) {
  const items = Array.isArray(turn?.items) ? turn.items : []
  return items
    .filter(item => item.type === 'mcpToolCall')
    .map(item => ({
      name: item.tool,
      status: item.status,
      account_id: getAccountID(item.arguments),
      server: item.server
    }))
}

function extractErosFileExports(turn) {
  const items = Array.isArray(turn?.items) ? turn.items : []
  const byKey = new Map()
  for (const item of items) {
    if (item?.type !== 'mcpToolCall') continue
    if (!['prepare_file_export', 'render_file_export'].includes(item.tool)) continue
    for (const candidate of findJSONObjects(item)) {
      const hint = sanitizeFileExportHint(candidate)
      if (!hint) continue
      const key = `${hint.format || ''}|${hint.filename || ''}|${hint.title || ''}`
      const existing = byKey.get(key)
      if (!existing || (!existing.content && hint.content) || item.tool === 'render_file_export') {
        byKey.set(key, hint)
      }
    }
  }
  return [...byKey.values()].slice(0, 3)
}

function findJSONObjects(value, depth = 0) {
  if (depth > 6 || value == null) return []
  if (typeof value === 'string') {
    const text = value.trim()
    if (!text || text.length > 1000000) return []
    try {
      return findJSONObjects(JSON.parse(text), depth + 1)
    } catch {
      return []
    }
  }
  if (Array.isArray(value)) return value.flatMap(item => findJSONObjects(item, depth + 1))
  if (typeof value === 'object') {
    const found = []
    if (value.eros_file_export === true || value.file_export === true || value.download_delivery === 'clarin_chat_attachment') {
      found.push(value)
    }
    for (const child of Object.values(value)) {
      found.push(...findJSONObjects(child, depth + 1))
    }
    return found
  }
  return []
}

function sanitizeFileExportHint(value) {
  if (!value || typeof value !== 'object') return null
  const format = normalizeFileFormat(value.format || value.file_format || value.type)
  if (!format) return null
  return {
    format,
    filename: safeShortText(value.filename || value.file_name || ''),
    title: safeShortText(value.title || value.name || ''),
    content: safeFileContent(value.content || value.file_content || value.markdown || value.text || contentFromLegacySource(value.source))
  }
}

function normalizeFileFormat(value) {
  const text = String(value || '').trim().toLowerCase().replace(/^\./, '')
  if (['txt', 'text', 'texto'].includes(text)) return 'txt'
  if (text === 'csv') return 'csv'
  if (['xlsx', 'excel'].includes(text)) return 'xlsx'
  if (['docx', 'doc', 'word'].includes(text)) return 'docx'
  if (['pptx', 'ppt', 'powerpoint'].includes(text)) return 'pptx'
  if (text === 'pdf') return 'pdf'
  return ''
}

function safeShortText(value) {
  return String(value || '').replace(/[^\w .-]+/g, '_').trim().slice(0, 120)
}

function safeFileContent(value) {
  return String(value || '').trim().slice(0, 750000)
}

function contentFromLegacySource(value) {
  const text = String(value || '').trim()
  if (!text || text === 'assistant_response' || text.length < 80 || !/[\n|,;]/.test(text)) return ''
  return text
}

function getAccountID(args) {
  if (typeof args === 'string') {
    try {
      args = JSON.parse(args)
    } catch {
      return ''
    }
  }
  if (!args || typeof args !== 'object') return ''
  const value = args.account_id || args.accountId
  return typeof value === 'string' ? value : ''
}

function summarizeTurnForLog(turn) {
  const items = Array.isArray(turn?.items) ? turn.items : []
  const counts = new Map()
  for (const item of items) {
    const type = item && typeof item.type === 'string' ? item.type : 'unknown'
    counts.set(type, (counts.get(type) || 0) + 1)
  }
  const itemTypes = [...counts.entries()].map(([type, count]) => `${type}:${count}`).join(',')
  return [
    `status=${turn?.status || 'unknown'}`,
    `itemsView=${turn?.itemsView || 'unknown'}`,
    `itemCount=${items.length}`,
    `itemTypes=${itemTypes || 'none'}`,
    `error=${summarizeTurnError(turn)}`
  ].join(' ')
}

function summarizeTurnError(turn) {
  const error = turn?.error || {}
  const code = error.codexErrorInfo ? JSON.stringify(error.codexErrorInfo) : ''
  const message = error.message ? redactError(String(error.message)).slice(0, 240) : ''
  return [code, message].filter(Boolean).join(': ') || 'none'
}

const app = new CodexAppServer()

async function readJSON(req) {
  const chunks = []
  let size = 0
  for await (const chunk of req) {
    size += chunk.length
    if (size > 1024 * 1024) throw new Error('request body too large')
    chunks.push(chunk)
  }
  const raw = Buffer.concat(chunks).toString('utf8')
  return raw ? JSON.parse(raw) : {}
}

function sendJSON(res, status, body) {
  const payload = JSON.stringify(body)
  res.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'content-length': Buffer.byteLength(payload),
    'cache-control': 'no-store'
  })
  res.end(payload)
}

async function health() {
  const status = {
    ok: false,
    bridge: 'clarin-codex-bridge',
    codex_running: Boolean(app.proc && app.proc.exitCode === null),
    codex_initialized: app.initialized,
    codex_auth_persisted: await exists(path.join(CODEX_HOME, 'auth.json')),
    codex_authenticated: false,
    codex_auth_rejected: false,
    codex_auth_error: null,
    codex_auth_error_detected_at: null,
    codex_auth_mode: null,
    codex_account_email: '',
    codex_plan_type: '',
    device_login_status: app.deviceLogin.status,
    mcp_base_url_configured: Boolean(MCP_BASE_URL),
    mcp_access_token_configured: Boolean(MCP_TOKEN),
    mcp_server: MCP_SERVER_NAME,
    codex_model: CODEX_MODEL || null,
    reasoning_effort: CODEX_REASONING_EFFORT || null,
    mcp_tools_count: 0,
    mcp_auth_status: null
  }
  try {
    const connection = await app.getConnectionStatus()
    status.codex_authenticated = connection.connected
    status.codex_auth_rejected = Boolean(connection.error)
    status.codex_auth_error = connection.error
    status.codex_auth_error_detected_at = app.authIssue?.detected_at || null
    status.codex_auth_mode = connection.auth_mode
    status.codex_account_email = connection.email
    status.codex_plan_type = connection.plan_type
    status.codex_requires_openai_auth = connection.requires_openai_auth
    status.device_login_status = connection.login.status
    if (!connection.connected) {
      status.error = connection.error || 'codex_auth_required'
      return status
    }
    const mcp = await app.mcpStatus()
    const clarin = (mcp.data || []).find(s => s.name === MCP_SERVER_NAME)
    if (clarin) {
      status.mcp_auth_status = clarin.authStatus || null
      status.mcp_tools_count = clarin.tools ? Object.keys(clarin.tools).length : 0
    }
    status.ok = Boolean(app.initialized && status.codex_authenticated && status.mcp_tools_count > 0)
  } catch (err) {
    status.error = redactError(err)
  }
  return status
}

const server = createServer(async (req, res) => {
  try {
    if (req.url === '/live' && req.method === 'GET') {
      if (!hasBridgeAccess(req)) return sendJSON(res, 401, { success: false, error: 'unauthorized' })
      return sendJSON(res, 200, { success: true, ok: true, bridge: 'clarin-codex-bridge' })
    }
    if (req.url === '/health' && req.method === 'GET') {
      if (!hasBridgeAccess(req)) return sendJSON(res, 401, { success: false, error: 'unauthorized' })
      const body = await health()
      return sendJSON(res, body.ok ? 200 : 503, { success: body.ok, ...body })
    }
    if (req.url === '/chat' && req.method === 'POST') {
      if (!hasBridgeAccess(req)) return sendJSON(res, 401, { success: false, error: 'unauthorized' })
      const body = await readJSON(req)
      if (!body.account_id || !body.user_id || !body.conversation_id || !body.message) {
        return sendJSON(res, 400, { success: false, error: 'missing required Eros bridge fields' })
      }
      const result = await app.chat(body)
      return sendJSON(res, 200, result)
    }
    if (req.url === '/auth/status' && req.method === 'GET') {
      if (!hasBridgeAccess(req)) return sendJSON(res, 401, { success: false, error: 'unauthorized' })
      return sendJSON(res, 200, { success: true, connection: await app.getConnectionStatus() })
    }
    if (req.url === '/auth/device/start' && req.method === 'POST') {
      if (!hasBridgeAccess(req)) return sendJSON(res, 401, { success: false, error: 'unauthorized' })
      const login = await app.startDeviceLogin()
      return sendJSON(res, 200, { success: true, login })
    }
    if (req.url === '/auth/device/cancel' && req.method === 'POST') {
      if (!hasBridgeAccess(req)) return sendJSON(res, 401, { success: false, error: 'unauthorized' })
      const body = await readJSON(req)
      const login = await app.cancelDeviceLogin(String(body.login_id || ''))
      return sendJSON(res, 200, { success: true, login })
    }
    if (req.url === '/auth/logout' && req.method === 'POST') {
      if (!hasBridgeAccess(req)) return sendJSON(res, 401, { success: false, error: 'unauthorized' })
      const connection = await app.logout()
      return sendJSON(res, 200, { success: true, connection })
    }
    return sendJSON(res, 404, { success: false, error: 'not_found' })
  } catch (err) {
    if (isCodexAuthError(err)) {
      return sendJSON(res, 503, {
        success: false,
        error: err.code || 'codex_auth_revoked',
        detail: err.detail || 'Codex ChatGPT auth was rejected by ChatGPT.'
      })
    }
    if (String(req.url || '').startsWith('/auth/')) {
      console.error(`[eros] OpenAI connection endpoint failed: ${redactError(err)}`)
      return sendJSON(res, 502, {
        success: false,
        error: 'openai_connection_failed',
        detail: 'The OpenAI connection could not be completed.'
      })
    }
    return sendJSON(res, 500, { success: false, error: redactError(err) })
  }
})

if (!BRIDGE_TOKEN) {
  console.error('EROS_CODEX_BRIDGE_TOKEN is required; refusing to start an unprotected bridge.')
  process.exit(1)
}

server.listen(PORT, '0.0.0.0', () => {
  console.log(`clarin-codex-bridge listening on ${PORT}`)
})

process.on('SIGTERM', () => {
  if (app.proc) app.proc.kill('SIGTERM')
  server.close(() => process.exit(0))
})
