import { act, cleanup, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ client: { subscribe: vi.fn(), capabilities: vi.fn(), profile: vi.fn(), listLocalGrants: vi.fn(), prepare: vi.fn(), unlock: vi.fn(), lock: vi.fn(), replaceSelection: vi.fn(), gateway: vi.fn() }, availability: vi.fn(), grants: vi.fn(), selection: vi.fn(), candidates: vi.fn(), enabled: vi.fn(), enrollment: vi.fn() }))
vi.mock('@/offline-v4/client', () => ({ browserOfflineClient: mocks.client }))
vi.mock('@/lib/offlineV4ServiceWorker', () => ({ setOfflineV4NavigationEnabled: mocks.enabled, setOfflineV4Mode: vi.fn() }))
vi.mock('@/components/offline-v4/online', () => ({ offlineAvailabilityV4: mocks.availability, onlineGrantsV4: mocks.grants, grantSelectionV4: mocks.selection, resourceCandidatesV4: mocks.candidates, enrollmentStatusV4: mocks.enrollment }))
import OfflineAccessPanelV4 from './OfflineAccessPanelV4'

const grant = (id: string) => ({ grant_id: id, state: 'active', account_name: `Cuenta ${id}`, actions: ['contacts.read'], max_resources: 20, selection_revision: 1 })
const selection = (id: string) => ({ items: [{ module: 'contacts', resource_type: 'contact', resource_id: id, label: `Contacto ${id}` }], selection_revision: 1, selection_digest: 'digest' })
beforeEach(() => {
  vi.clearAllMocks()
  mocks.client.subscribe.mockReturnValue(() => {})
  mocks.client.capabilities.mockResolvedValue({ supported: true, persistent: true, usage: 0, quota: 1000000 })
  mocks.client.profile.mockResolvedValue({ browser_profile_id: 'browser', request_ids: [] })
  mocks.client.listLocalGrants.mockResolvedValue([])
  mocks.client.lock.mockResolvedValue(undefined)
  mocks.client.prepare.mockResolvedValue({ actor: { username: 'ana' } })
  mocks.availability.mockResolvedValue({ enabled: true })
  mocks.grants.mockResolvedValue({ items: [grant('A'), grant('B')] })
  mocks.selection.mockImplementation((id: string) => Promise.resolve(selection(id)))
  mocks.candidates.mockImplementation((id: string) => Promise.resolve({ items: selection(id).items }))
  mocks.enabled.mockResolvedValue(true)
})
afterEach(() => { cleanup(); vi.useRealTimers() })

describe('offline preparation account-scoped UI', () => {
  it('keeps the newest pending request instead of a previous approval', async () => {
    mocks.client.profile.mockResolvedValue({ browser_profile_id: 'browser', request_ids: ['new', 'old'] })
    mocks.enrollment.mockImplementation((id: string) => Promise.resolve({ request: { id, state: id === 'new' ? 'pending' : 'approved' } }))
    render(<OfflineAccessPanelV4 currentLogin="ana" />)
    await screen.findByLabelText('Contraseña de Clarin')
    expect(screen.getByRole('button', { name: 'Solicitar otra autorización' })).toBeDisabled()
    expect(mocks.enrollment.mock.calls.map(call => call[0])).toEqual(['new'])
  })
  it('skips another local user request and selects the newest accessible request', async () => {
    mocks.client.profile.mockResolvedValue({ browser_profile_id: 'browser', request_ids: ['foreign', 'new', 'old'] })
    mocks.enrollment.mockImplementation((id: string) => id === 'foreign' ? Promise.reject(new Error('not found')) : Promise.resolve({ request: { id, state: id === 'new' ? 'pending' : 'approved' } }))
    render(<OfflineAccessPanelV4 currentLogin="ana" />)
    await screen.findByLabelText('Contraseña de Clarin')
    expect(screen.getByRole('button', { name: 'Solicitar otra autorización' })).toBeDisabled()
    expect(mocks.enrollment.mock.calls.map(call => call[0])).toEqual(['foreign', 'new'])
  })
  it('does not retain a request when a refresh returns no accessible requests', async () => {
    mocks.client.profile.mockResolvedValueOnce({ browser_profile_id: 'browser', request_ids: ['new'] })
    mocks.enrollment.mockResolvedValue({ request: { id: 'new', state: 'pending' } })
    render(<OfflineAccessPanelV4 currentLogin="ana" />)
    await screen.findByLabelText('Contraseña de Clarin')
    expect(screen.getByRole('button', { name: 'Solicitar otra autorización' })).toBeDisabled()
    await act(async () => fireEvent.click(screen.getByRole('button', { name: /^Actualizar$/ })))
    expect(screen.getByRole('button', { name: 'Solicitar otra autorización' })).toBeEnabled()
  })
  it('renews an expired unchanged copy without requiring an expired offline unlock first', async () => {
    mocks.client.listLocalGrants.mockResolvedValue([{ grant_id: 'A', state: 'expired', label: 'Copia offline 1' }])
    render(<OfflineAccessPanelV4 currentLogin="ana" />)
    fireEvent.change(await screen.findByLabelText('Contraseña de Clarin'), { target: { value: 'secret-password-12' } })
    fireEvent.change(screen.getByLabelText('Repetir contraseña'), { target: { value: 'secret-password-12' } })
    fireEvent.click(screen.getByRole('button', { name: 'Actualizar y verificar copia' }))
    await screen.findByText(/^Copia verificada y lista\./)
    expect(mocks.client.prepare).toHaveBeenCalledExactlyOnceWith('A', 'secret-password-12')
    expect(mocks.client.unlock).not.toHaveBeenCalled()
    expect(screen.getByLabelText('Contraseña de Clarin')).toHaveValue('')
  })
  it('hides the previous account immediately while the next selection is loading', async () => {
    let finish!: (value: ReturnType<typeof selection>) => void
    mocks.selection.mockImplementation((id: string) => id === 'B' ? new Promise(resolve => { finish = resolve }) : Promise.resolve(selection(id)))
    render(<OfflineAccessPanelV4 currentLogin="ana" />)
    await screen.findByRole('button', { name: 'Quitar Contacto A' })
    fireEvent.click(screen.getByRole('button', { name: 'Cuenta B' }))
    expect(screen.queryByRole('button', { name: 'Quitar Contacto A' })).not.toBeInTheDocument()
    expect(screen.queryByLabelText('Contraseña de Clarin')).not.toBeInTheDocument()
    await act(async () => finish(selection('B')))
    expect(await screen.findByRole('button', { name: 'Quitar Contacto B' })).toBeInTheDocument()
    expect(screen.queryByText('Contacto A')).not.toBeInTheDocument()
  })
  it('starts search only at the exact 500ms boundary', async () => {
    render(<OfflineAccessPanelV4 currentLogin="ana" />)
    const input = await screen.findByLabelText('Buscar recursos autorizados')
    await act(async () => {})
    mocks.candidates.mockClear()
    vi.useFakeTimers()
    fireEvent.change(input, { target: { value: 'ultimo texto' } })
    await act(async () => { await vi.advanceTimersByTimeAsync(499) })
    expect(mocks.candidates).not.toHaveBeenCalled()
    await act(async () => { await vi.advanceTimersByTimeAsync(1) })
    expect(mocks.candidates).toHaveBeenCalledExactlyOnceWith('A', 'contacts', 'ultimo texto', '', expect.any(AbortSignal))
  })
})
