import { beforeEach, describe, expect, it, vi } from 'vitest'
import { beginAuthIdentityChange, completeAuthIdentityChange, getAuthScope, isAuthIdentityChanging, isAuthScopeSynchronized, subscribeAuthScope } from './authScope'

beforeEach(() => { localStorage.clear(); completeAuthIdentityChange() })
describe('authentication identity leases', () => {
  it('keeps ordinary reads stable and blocks work during an identity transition', () => {
    const original = getAuthScope()
    expect(getAuthScope()).toBe(original)
    const changing = beginAuthIdentityChange()
    expect(changing).not.toBe(original)
    expect(isAuthIdentityChanging()).toBe(true)
    const next = completeAuthIdentityChange()
    expect(next).not.toBe(changing)
    expect(isAuthIdentityChanging()).toBe(false)
  })
  it('notifies same-tab and cross-tab observers and releases subscriptions', () => {
    const listener = vi.fn()
    const release = subscribeAuthScope(listener)
    beginAuthIdentityChange()
    window.dispatchEvent(new StorageEvent('storage', { key: 'clarin:auth_scope', newValue: 'changing:other-tab' }))
    expect(listener).toHaveBeenCalledTimes(2)
    release()
    completeAuthIdentityChange()
    expect(listener).toHaveBeenCalledTimes(2)
  })
  it('keeps failed writes authoritative in memory and resynchronizes on another tab storage event', () => {
    const original = getAuthScope()
    expect(isAuthScopeSynchronized()).toBe(true)
    const write = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new DOMException('Quota exceeded', 'QuotaExceededError') })
    const changing = beginAuthIdentityChange()
    expect(localStorage.getItem('clarin:auth_scope')).toBe(original)
    expect(getAuthScope()).toBe(changing)
    expect(isAuthIdentityChanging()).toBe(true)
    expect(isAuthScopeSynchronized()).toBe(false)
    const active = completeAuthIdentityChange()
    expect(getAuthScope()).toBe(active)
    expect(getAuthScope()).not.toBe(original)
    expect(isAuthScopeSynchronized()).toBe(false)
    write.mockRestore()
    localStorage.setItem('clarin:auth_scope', 'active:other-tab-generation')
    window.dispatchEvent(new StorageEvent('storage', { key: 'clarin:auth_scope', newValue: 'active:other-tab-generation' }))
    expect(getAuthScope()).toBe('active:other-tab-generation')
    expect(isAuthScopeSynchronized()).toBe(true)
  })
})
